/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][1];
new Text:change_ped;
new PlayerText:play_button[MAX_PLAYERS];
new PlayerText:player_avatar[MAX_PLAYERS];
new PlayerText:friend_1[MAX_PLAYERS];
new PlayerText:friend_2[MAX_PLAYERS];
new PlayerText:friend_name_2[MAX_PLAYERS];
new PlayerText:friend_name_1[MAX_PLAYERS];
new PlayerText:playerName[MAX_PLAYERS];
new PlayerText:SelectMode[MAX_PLAYERS];
new PlayerText:SoloButton[MAX_PLAYERS];

public OnFilterScriptInit()
{
	change_ped = TextDrawCreate(601.000000, 396.000000, "HUD:radar_tshirt");
	TextDrawFont(change_ped, 4);
	TextDrawLetterSize(change_ped, 0.600000, 2.000000);
	TextDrawTextSize(change_ped, 26.500000, 26.500000);
	TextDrawSetOutline(change_ped, 0);
	TextDrawSetShadow(change_ped, 0);
	TextDrawAlignment(change_ped, 3);
	TextDrawColor(change_ped, -1);
	TextDrawBackgroundColor(change_ped, -2016478465);
	TextDrawBoxColor(change_ped, 50);
	TextDrawUseBox(change_ped, 1);
	TextDrawSetProportional(change_ped, 1);
	TextDrawSetSelectable(change_ped, 1);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(change_ped);
	return 1;
}

public OnPlayerConnect(playerid)
{
	play_button[playerid] = CreatePlayerTextDraw(playerid, 71.000000, 382.000000, "Play");
	PlayerTextDrawFont(playerid, play_button[playerid], 2);
	PlayerTextDrawLetterSize(playerid, play_button[playerid], 0.437498, 4.750000);
	PlayerTextDrawTextSize(playerid, play_button[playerid], 304.500000, 105.500000);
	PlayerTextDrawSetOutline(playerid, play_button[playerid], 1);
	PlayerTextDrawSetShadow(playerid, play_button[playerid], 0);
	PlayerTextDrawAlignment(playerid, play_button[playerid], 2);
	PlayerTextDrawColor(playerid, play_button[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, play_button[playerid], 255);
	PlayerTextDrawBoxColor(playerid, play_button[playerid], 200);
	PlayerTextDrawUseBox(playerid, play_button[playerid], 1);
	PlayerTextDrawSetProportional(playerid, play_button[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, play_button[playerid], 1);

	player_avatar[playerid] = CreatePlayerTextDraw(playerid, 239.000000, 69.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, player_avatar[playerid], 5);
	PlayerTextDrawLetterSize(playerid, player_avatar[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, player_avatar[playerid], 150.000000, 232.000000);
	PlayerTextDrawSetOutline(playerid, player_avatar[playerid], 0);
	PlayerTextDrawSetShadow(playerid, player_avatar[playerid], 0);
	PlayerTextDrawAlignment(playerid, player_avatar[playerid], 1);
	PlayerTextDrawColor(playerid, player_avatar[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, player_avatar[playerid], 125);
	PlayerTextDrawBoxColor(playerid, player_avatar[playerid], 255);
	PlayerTextDrawUseBox(playerid, player_avatar[playerid], 0);
	PlayerTextDrawSetProportional(playerid, player_avatar[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, player_avatar[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, player_avatar[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, player_avatar[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, player_avatar[playerid], 1, 1);

	friend_1[playerid] = CreatePlayerTextDraw(playerid, 393.000000, 69.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, friend_1[playerid], 5);
	PlayerTextDrawLetterSize(playerid, friend_1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, friend_1[playerid], 150.000000, 232.000000);
	PlayerTextDrawSetOutline(playerid, friend_1[playerid], 0);
	PlayerTextDrawSetShadow(playerid, friend_1[playerid], 0);
	PlayerTextDrawAlignment(playerid, friend_1[playerid], 1);
	PlayerTextDrawColor(playerid, friend_1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, friend_1[playerid], 125);
	PlayerTextDrawBoxColor(playerid, friend_1[playerid], 255);
	PlayerTextDrawUseBox(playerid, friend_1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, friend_1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, friend_1[playerid], 1);
	PlayerTextDrawSetPreviewModel(playerid, friend_1[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, friend_1[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, friend_1[playerid], 1, 1);

	friend_2[playerid] = CreatePlayerTextDraw(playerid, 85.000000, 70.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, friend_2[playerid], 5);
	PlayerTextDrawLetterSize(playerid, friend_2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, friend_2[playerid], 150.000000, 232.000000);
	PlayerTextDrawSetOutline(playerid, friend_2[playerid], 0);
	PlayerTextDrawSetShadow(playerid, friend_2[playerid], 0);
	PlayerTextDrawAlignment(playerid, friend_2[playerid], 1);
	PlayerTextDrawColor(playerid, friend_2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, friend_2[playerid], 125);
	PlayerTextDrawBoxColor(playerid, friend_2[playerid], 255);
	PlayerTextDrawUseBox(playerid, friend_2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, friend_2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, friend_2[playerid], 1);
	PlayerTextDrawSetPreviewModel(playerid, friend_2[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, friend_2[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, friend_2[playerid], 1, 1);

	friend_name_2[playerid] = CreatePlayerTextDraw(playerid, 160.000000, 46.000000, "TextDraw");
	PlayerTextDrawFont(playerid, friend_name_2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, friend_name_2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, friend_name_2[playerid], 400.000000, 141.500000);
	PlayerTextDrawSetOutline(playerid, friend_name_2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, friend_name_2[playerid], 0);
	PlayerTextDrawAlignment(playerid, friend_name_2[playerid], 2);
	PlayerTextDrawColor(playerid, friend_name_2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, friend_name_2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, friend_name_2[playerid], 50);
	PlayerTextDrawUseBox(playerid, friend_name_2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, friend_name_2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, friend_name_2[playerid], 0);

	friend_name_1[playerid] = CreatePlayerTextDraw(playerid, 467.000000, 46.000000, "TextDraw");
	PlayerTextDrawFont(playerid, friend_name_1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, friend_name_1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, friend_name_1[playerid], 400.000000, 141.500000);
	PlayerTextDrawSetOutline(playerid, friend_name_1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, friend_name_1[playerid], 0);
	PlayerTextDrawAlignment(playerid, friend_name_1[playerid], 2);
	PlayerTextDrawColor(playerid, friend_name_1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, friend_name_1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, friend_name_1[playerid], 50);
	PlayerTextDrawUseBox(playerid, friend_name_1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, friend_name_1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, friend_name_1[playerid], 0);

	playerName[playerid] = CreatePlayerTextDraw(playerid, 314.000000, 45.000000, "TextDraw");
	PlayerTextDrawFont(playerid, playerName[playerid], 1);
	PlayerTextDrawLetterSize(playerid, playerName[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, playerName[playerid], 400.000000, 141.500000);
	PlayerTextDrawSetOutline(playerid, playerName[playerid], 1);
	PlayerTextDrawSetShadow(playerid, playerName[playerid], 0);
	PlayerTextDrawAlignment(playerid, playerName[playerid], 2);
	PlayerTextDrawColor(playerid, playerName[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, playerName[playerid], 255);
	PlayerTextDrawBoxColor(playerid, playerName[playerid], 50);
	PlayerTextDrawUseBox(playerid, playerName[playerid], 1);
	PlayerTextDrawSetProportional(playerid, playerName[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, playerName[playerid], 0);

	SelectMode[playerid] = CreatePlayerTextDraw(playerid, 50.000000, 325.000000, "Select Mode");
	PlayerTextDrawFont(playerid, SelectMode[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SelectMode[playerid], 0.337500, 1.950000);
	PlayerTextDrawTextSize(playerid, SelectMode[playerid], 400.000000, 103.000000);
	PlayerTextDrawSetOutline(playerid, SelectMode[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SelectMode[playerid], 2);
	PlayerTextDrawAlignment(playerid, SelectMode[playerid], 2);
	PlayerTextDrawColor(playerid, SelectMode[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SelectMode[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SelectMode[playerid], 50);
	PlayerTextDrawUseBox(playerid, SelectMode[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SelectMode[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SelectMode[playerid], 0);

	SoloButton[playerid] = CreatePlayerTextDraw(playerid, 37.000000, 357.000000, "Solo");
	PlayerTextDrawFont(playerid, SoloButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, SoloButton[playerid], 0.258332, 1.750000);
	PlayerTextDrawTextSize(playerid, SoloButton[playerid], 16.500000, 32.000000);
	PlayerTextDrawSetOutline(playerid, SoloButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SoloButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, SoloButton[playerid], 2);
	PlayerTextDrawColor(playerid, SoloButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SoloButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SoloButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, SoloButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SoloButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SoloButton[playerid], 1);

	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 101.000000, 357.000000, "Squad");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.258332, 1.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 16.500000, 39.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 200);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, play_button[playerid]);
	PlayerTextDrawDestroy(playerid, player_avatar[playerid]);
	PlayerTextDrawDestroy(playerid, friend_1[playerid]);
	PlayerTextDrawDestroy(playerid, friend_2[playerid]);
	PlayerTextDrawDestroy(playerid, friend_name_2[playerid]);
	PlayerTextDrawDestroy(playerid, friend_name_1[playerid]);
	PlayerTextDrawDestroy(playerid, playerName[playerid]);
	PlayerTextDrawDestroy(playerid, SelectMode[playerid]);
	PlayerTextDrawDestroy(playerid, SoloButton[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, change_ped);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, play_button[playerid]);
		PlayerTextDrawShow(playerid, player_avatar[playerid]);
		PlayerTextDrawShow(playerid, friend_1[playerid]);
		PlayerTextDrawShow(playerid, friend_2[playerid]);
		PlayerTextDrawShow(playerid, friend_name_2[playerid]);
		PlayerTextDrawShow(playerid, friend_name_1[playerid]);
		PlayerTextDrawShow(playerid, playerName[playerid]);
		PlayerTextDrawShow(playerid, SelectMode[playerid]);
		PlayerTextDrawShow(playerid, SoloButton[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
