/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:pedPreview[MAX_PLAYERS];
new PlayerText:backButton[MAX_PLAYERS];
new PlayerText:nextButton[MAX_PLAYERS];
new PlayerText:selectButton[MAX_PLAYERS];
new PlayerText:returnToMenu[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	pedPreview[playerid] = CreatePlayerTextDraw(playerid, 215.000000, 72.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, pedPreview[playerid], 5);
	PlayerTextDrawLetterSize(playerid, pedPreview[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, pedPreview[playerid], 202.500000, 265.000000);
	PlayerTextDrawSetOutline(playerid, pedPreview[playerid], 0);
	PlayerTextDrawSetShadow(playerid, pedPreview[playerid], 0);
	PlayerTextDrawAlignment(playerid, pedPreview[playerid], 1);
	PlayerTextDrawColor(playerid, pedPreview[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, pedPreview[playerid], 125);
	PlayerTextDrawBoxColor(playerid, pedPreview[playerid], 255);
	PlayerTextDrawUseBox(playerid, pedPreview[playerid], 0);
	PlayerTextDrawSetProportional(playerid, pedPreview[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, pedPreview[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, pedPreview[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, pedPreview[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, pedPreview[playerid], 1, 1);

	backButton[playerid] = CreatePlayerTextDraw(playerid, 262.000000, 341.000000, "Back");
	PlayerTextDrawFont(playerid, backButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, backButton[playerid], 0.258332, 1.750000);
	PlayerTextDrawTextSize(playerid, backButton[playerid], 16.500000, 90.500000);
	PlayerTextDrawSetOutline(playerid, backButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, backButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, backButton[playerid], 2);
	PlayerTextDrawColor(playerid, backButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, backButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, backButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, backButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, backButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, backButton[playerid], 1);

	nextButton[playerid] = CreatePlayerTextDraw(playerid, 369.000000, 341.000000, "Next");
	PlayerTextDrawFont(playerid, nextButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, nextButton[playerid], 0.258332, 1.750000);
	PlayerTextDrawTextSize(playerid, nextButton[playerid], 16.500000, 90.500000);
	PlayerTextDrawSetOutline(playerid, nextButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, nextButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, nextButton[playerid], 2);
	PlayerTextDrawColor(playerid, nextButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, nextButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, nextButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, nextButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, nextButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, nextButton[playerid], 1);

	selectButton[playerid] = CreatePlayerTextDraw(playerid, 316.000000, 365.000000, "Select");
	PlayerTextDrawFont(playerid, selectButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, selectButton[playerid], 0.258332, 1.750000);
	PlayerTextDrawTextSize(playerid, selectButton[playerid], 16.500000, 90.500000);
	PlayerTextDrawSetOutline(playerid, selectButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, selectButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, selectButton[playerid], 2);
	PlayerTextDrawColor(playerid, selectButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, selectButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, selectButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, selectButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, selectButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, selectButton[playerid], 1);

	returnToMenu[playerid] = CreatePlayerTextDraw(playerid, 603.000000, 405.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, returnToMenu[playerid], 4);
	PlayerTextDrawLetterSize(playerid, returnToMenu[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, returnToMenu[playerid], 32.500000, 38.000000);
	PlayerTextDrawSetOutline(playerid, returnToMenu[playerid], 1);
	PlayerTextDrawSetShadow(playerid, returnToMenu[playerid], 0);
	PlayerTextDrawAlignment(playerid, returnToMenu[playerid], 1);
	PlayerTextDrawColor(playerid, returnToMenu[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, returnToMenu[playerid], 255);
	PlayerTextDrawBoxColor(playerid, returnToMenu[playerid], 50);
	PlayerTextDrawUseBox(playerid, returnToMenu[playerid], 1);
	PlayerTextDrawSetProportional(playerid, returnToMenu[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, returnToMenu[playerid], 1);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, pedPreview[playerid]);
	PlayerTextDrawDestroy(playerid, backButton[playerid]);
	PlayerTextDrawDestroy(playerid, nextButton[playerid]);
	PlayerTextDrawDestroy(playerid, selectButton[playerid]);
	PlayerTextDrawDestroy(playerid, returnToMenu[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, pedPreview[playerid]);
		PlayerTextDrawShow(playerid, backButton[playerid]);
		PlayerTextDrawShow(playerid, nextButton[playerid]);
		PlayerTextDrawShow(playerid, selectButton[playerid]);
		PlayerTextDrawShow(playerid, returnToMenu[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
